apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: authorino
  namespace: openshift-operators
spec:
  channel: "stable"
  installPlanApproval: Automatic
  name: authorino-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace