---
# Default variables for RHACM role
rhacm_operator_namespace: open-cluster-management
rhacm_operator_name: advanced-cluster-management
rhacm_operator_channel: release-2.11
rhacm_operator_source: redhat-operators

rhacm_namespace: open-cluster-management
rhacm_hub_namespace: open-cluster-management-hub

