apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: devspaces
  namespace: openshift-devspaces 
spec:
  channel: stable
  name: devspaces
  source: redhat-operators 
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic
  # ROLEARN will be set by Ansible (ansible/roles/rhacm/tasks/configure_devspaces_role.yml)
  # The config section will be added automatically when Ansible runs 
