apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: operators
  namespace: openshift-gitops
spec:
  generators:
  - list:
      elements:
      # NFD Operator
      - operator: nfd-operator
        namespace: openshift-nfd
      # NVIDIA GPU Operator
      - operator: nvidia-operator
        namespace: nvidia-gpu-operator
      # OpenShift AI Operator
      - operator: openshift-ai
        namespace: redhat-ods-operator
      # Authorino Operator
      - operator: authorino
        namespace: openshift-operators
      # Cloud Native PostgreSQL Operator
      - operator: cnpg-operator
        namespace: cnpg-system
      # Keycloak Operator
      - operator: keycloak-operator
        namespace: keycloak-operator
      # DevSpaces Operator
      - operator: devspaces
        namespace: openshift-devspaces
  template:
    metadata:
      name: '{{operator}}-operator'
      namespace: openshift-gitops
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: https://github.com/kanekoh/mta-workshop-env.git
        targetRevision: main
        path: gitops/operators/{{operator}}
        directory:
          recurse: true
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground
          - PruneLast=true

