apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: cloud-native-postgresql
  namespace: cnpg-system
spec:
  channel: "stable-v1.26"
  installPlanApproval: Automatic
  name: cloud-native-postgresql
  source: certified-operators
  sourceNamespace: openshift-marketplace

